---
- name: Update all packages (apt-get update+upgrade)
  action: apt update_cache=yes upgrade=full cache_valid_time=3600

- name: Install necessary ubuntu packages
  action: apt name={{ item }} state=installed
  with_items: lts14lizardbox_packages

- name: Install missing mapnik egg-info file.
  action: copy
  args:
    src: mapnik-2.2.0.egg-info
    dest: /usr/lib/python2.7/dist-packages/mapnik-2.2.0.egg-info
